### ISSUE TITLE
Missing state parameter in getUserConsentUrl

### ISSUE THREAD

**Issue by mattia85** [pajaydev/oauth-ebay#11]
Hi,
please add `state` parameter to **getUserConsentUrl**  method in order to use it to generate the authorization url according with ebay doc.

```
/* URL redirects a user to the application's Grant Application Access page */

  https://auth.sandbox.ebay.com/oauth2/authorize?
    client_id=<app-client-id-value>&
    redirect_uri=<app-RuName-value>&
    response_type=code&
    state=<custom-state-value>&
    scope=<scopeList>   // a URL-encoded string of space-separated scopes
```

Thanks
Mattia

**Comment by pajaydev** [comment]
@mattia85  Fixed it. you will get it in the latest version
`npm install oauth-ebay@1.3.3`

Quick note:
Moving forward use this official ebay package. https://github.com/eBay/ebay-oauth-nodejs-client
